/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.controllerAgregarImagen;
import Controller.controllerEstudiante;
import Model.preguntas;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Mariano
 */
public class JFInterfazAlumno extends javax.swing.JFrame {

    /**
     * Creates new form JFInterfazAlumno
     */
    controllerEstudiante controllerEstudiante;
    controllerAgregarImagen controller3;
    public JFInterfazAlumno() {
        initComponents();
  
        
        txtExplicacion.setEnabled(false);
        ButtonGroup bg = new ButtonGroup();
        bg.add(panelPregunta11.radioA);
        bg.add(panelPregunta11.radioB);
        bg.add(panelPregunta11.radioC);
        bg.add(panelPregunta11.radioD);
        
        bg.add(panelPregunta21.radioA);
        bg.add(panelPregunta21.radioB);
        bg.add(panelPregunta21.radioC);
        bg.add(panelPregunta21.radioD);
        
        bg.add(panelPregunta31.radioA);
        bg.add(panelPregunta31.radioB);
        bg.add(panelPregunta31.radioC);
        bg.add(panelPregunta31.radioD);

        panelPregunta11.txtPregunta.setEditable(false);
        panelPregunta11.txtA.setEditable(false);
        panelPregunta11.txtB.setEditable(false);
        panelPregunta11.txtC.setEditable(false);
        panelPregunta11.txtD.setEditable(false);
        
        panelPregunta21.txtPregunta.setEditable(false);
        panelPregunta21.txtPregunta1.setEditable(false);
        panelPregunta21.txtA.setEditable(false);
        panelPregunta21.txtB.setEditable(false);
        panelPregunta21.txtC.setEditable(false);
        panelPregunta21.txtD.setEditable(false);
        
        panelPregunta31.txtA.setEditable(false);
        panelPregunta31.txtB.setEditable(false);
        panelPregunta31.txtC.setEditable(false);
        panelPregunta31.txtD.setEditable(false);
        
        
        controllerEstudiante.setPregunta("1");
        controllerEstudiante.firstFillPreguntas();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelPregunta11 = new GUI.panelPregunta1();
        panelPregunta21 = new GUI.panelPregunta2();
        panelPregunta31 = new GUI.panelPregunta3();
        jLabel5 = new javax.swing.JLabel();
        btnVerImagen = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        labelSubtema = new javax.swing.JLabel();
        btnVerTexto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelImagen = new javax.swing.JLabel();
        txtExplicacion = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(597, 648));
        setMinimumSize(new java.awt.Dimension(597, 648));
        setResizable(false);

        jTabbedPane1.addTab("Patron 1", panelPregunta11);
        jTabbedPane1.addTab("Patron 2", panelPregunta21);
        jTabbedPane1.addTab("Patron 3", panelPregunta31);

        jLabel5.setText("Escoja Subtema:");

        btnVerImagen.setText("Ver Imagen");
        btnVerImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerImagenActionPerformed(evt);
            }
        });

        jLabel4.setText("Imagen:");

        jLabel3.setText("Textual:");

        jLabel2.setText("Tipo de Explicación:");

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        labelSubtema.setText("nombreSubtema");

        btnVerTexto.setText("Ver Texto");
        btnVerTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTextoActionPerformed(evt);
            }
        });

        jLabel6.setText("Numero de Pregunta:");

        labelNumero.setText("1");

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        labelImagen.setText(".");
        jScrollPane2.setViewportView(labelImagen);

        txtExplicacion.setEditable(false);
        txtExplicacion.setMaximumSize(new java.awt.Dimension(50, 50));
        txtExplicacion.setMinimumSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(35, 35, 35)
                                .addComponent(btnVerTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtExplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(labelNumero)))
                                    .addGap(364, 364, 364))
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(labelSubtema)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(53, 53, 53)
                                .addComponent(btnVerImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAnterior)
                        .addGap(18, 18, 18)
                        .addComponent(btnSiguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizar)
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnVerImagen)
                    .addComponent(jLabel3)
                    .addComponent(btnVerTexto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addComponent(txtExplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelSubtema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente)
                    .addComponent(btnFinalizar))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        int panelIndex=jTabbedPane1.getSelectedIndex();
        String respuesta="";
        switch(panelIndex){
            case 0:
                if(panelPregunta11.radioA.isSelected()){
                    respuesta=panelPregunta11.txtA.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                if(panelPregunta11.radioB.isSelected()){
                    respuesta=panelPregunta11.txtB.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                if(panelPregunta11.radioC.isSelected()){
                    respuesta=panelPregunta11.txtC.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                if(panelPregunta11.radioD.isSelected()){
                    respuesta=panelPregunta11.txtD.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                break;
            case 1:
                if(panelPregunta21.radioA.isSelected()){
                    respuesta=panelPregunta21.txtA.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                if(panelPregunta21.radioB.isSelected()){
                    respuesta=panelPregunta21.txtB.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                if(panelPregunta21.radioC.isSelected()){
                    respuesta=panelPregunta21.txtC.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                if(panelPregunta21.radioD.isSelected()){
                    respuesta=panelPregunta21.txtD.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                break;
            case 2:
                if(panelPregunta31.radioA.isSelected()){
                    respuesta=panelPregunta31.txtA.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                if(panelPregunta31.radioB.isSelected()){
                    respuesta=panelPregunta31.txtB.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                if(panelPregunta31.radioC.isSelected()){
                    respuesta=panelPregunta31.txtC.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                if(panelPregunta31.radioD.isSelected()){
                    respuesta=panelPregunta31.txtD.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                break;
        }
        String res=controllerEstudiante.calificar();
        this.dispose();
        JOptionPane.showMessageDialog(null, res);
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnVerImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerImagenActionPerformed
        controllerEstudiante.changeStateQuestion(labelNumero.getText(),"Help");
    }//GEN-LAST:event_btnVerImagenActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        int panelIndex=jTabbedPane1.getSelectedIndex();
        String respuesta="";
        switch(panelIndex){
            case 0:
                if(panelPregunta11.radioA.isSelected()){
                    respuesta=panelPregunta11.txtA.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                    System.out.println(respuesta);
                    return;
                }
                if(panelPregunta11.radioB.isSelected()){
                    respuesta=panelPregunta11.txtB.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                    System.out.println(respuesta);
                    return;
                }
                if(panelPregunta11.radioC.isSelected()){
                    respuesta=panelPregunta11.txtC.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                    System.out.println(respuesta);
                    return;
                }
                if(panelPregunta11.radioD.isSelected()){
                    respuesta=panelPregunta11.txtD.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                    System.out.println(respuesta);
                    return;
                }
               controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),"Unanswered");
                break;
                
            case 1:
                if(panelPregunta21.radioA.isSelected()){
                    respuesta=panelPregunta21.txtA.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                    return;
                }
                if(panelPregunta21.radioB.isSelected()){
                    respuesta=panelPregunta21.txtB.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                    return;
                }
                if(panelPregunta11.radioC.isSelected()){
                    respuesta=panelPregunta21.txtC.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                    return;
                }
                if(panelPregunta21.radioD.isSelected()){
                    respuesta=panelPregunta21.txtD.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                    return;
                }
                controllerEstudiante.changeStateQuestion(
                labelNumero.getText(),"Unanswered");
                break;
            case 2:
                if(panelPregunta31.radioA.isSelected()){
                    respuesta=panelPregunta31.txtA.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                    return;
                }
                if(panelPregunta31.radioB.isSelected()){
                    respuesta=panelPregunta31.txtB.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                    return;
                }
                if(panelPregunta31.radioC.isSelected()){
                    respuesta=panelPregunta31.txtC.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                    return;
                }
                if(panelPregunta31.radioD.isSelected()){
                    respuesta=panelPregunta31.txtD.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                    return;
                }
                controllerEstudiante.changeStateQuestion(
                labelNumero.getText(),"Unanswered");
                
                break;
           
               
                
        }
        
        String numeroPregunta=labelNumero.getText();
        if (!numeroPregunta.equalsIgnoreCase("1")){
            int numero= Integer.parseInt(numeroPregunta);
            numero-=1;
            numeroPregunta=String.valueOf(numero);
            labelNumero.setText(numeroPregunta);
            controllerEstudiante.setPregunta(numeroPregunta);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No hay más preguntas"
                    + " hacia atrás!");
        }
        
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        String numeroPregunta=labelNumero.getText();
        preguntas p=new preguntas();
        int maximo=p.getMajorID();
        String maximoS=String.valueOf(maximo);
        
        int panelIndex=jTabbedPane1.getSelectedIndex();
        String respuesta="";
        switch(panelIndex){
            case 0:
                if(panelPregunta11.radioA.isSelected()){
                    respuesta=panelPregunta11.txtA.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                    System.out.println(labelNumero.getText()+" "+respuesta);
                }
                if(panelPregunta11.radioB.isSelected()){
                    respuesta=panelPregunta11.txtB.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                    System.out.println(labelNumero.getText()+" "+respuesta);
                }
                if(panelPregunta11.radioC.isSelected()){
                    respuesta=panelPregunta11.txtC.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                    System.out.println(labelNumero.getText()+" "+respuesta);
                }
                if(panelPregunta11.radioD.isSelected()){
                    respuesta=panelPregunta11.txtD.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                    System.out.println(labelNumero.getText()+" "+respuesta);
                }
                break;
            case 1:
                if(panelPregunta11.radioA.isSelected()){
                    respuesta=panelPregunta21.txtA.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                if(panelPregunta11.radioB.isSelected()){
                    respuesta=panelPregunta21.txtB.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                if(panelPregunta11.radioC.isSelected()){
                    respuesta=panelPregunta21.txtC.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                if(panelPregunta11.radioD.isSelected()){
                    respuesta=panelPregunta21.txtD.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                break;
            case 2:
                if(panelPregunta11.radioA.isSelected()){
                    respuesta=panelPregunta31.txtA.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                if(panelPregunta11.radioB.isSelected()){
                    respuesta=panelPregunta31.txtB.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                if(panelPregunta11.radioC.isSelected()){
                    respuesta=panelPregunta31.txtC.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                if(panelPregunta11.radioD.isSelected()){
                    respuesta=panelPregunta31.txtD.getText();
                    controllerEstudiante.changeStateQuestion(
                            labelNumero.getText(),respuesta);
                }
                break;
        }
        
        if (!numeroPregunta.equalsIgnoreCase(maximoS)){
            int numero= Integer.parseInt(numeroPregunta);
            numero+=1;
            numeroPregunta=String.valueOf(numero);
            labelNumero.setText(numeroPregunta);
            
            ArrayList <String> pregunta=new ArrayList<String>();
            pregunta=preguntas.mostrarPreguntasXID(numeroPregunta);
            controllerEstudiante.setPregunta(numeroPregunta);
        }
        else{
            JOptionPane.showMessageDialog(null, "No hay más preguntas");
        }
        
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnVerTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTextoActionPerformed
        controllerEstudiante.changeStateQuestion(labelNumero.getText(),"Help");
        JFInterfazAlumno.txtExplicacion.setVisible(true);
        JFInterfazAlumno.txtExplicacion.revalidate();
        
    }//GEN-LAST:event_btnVerTextoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFInterfazAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFInterfazAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFInterfazAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFInterfazAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFInterfazAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAnterior;
    public static javax.swing.JButton btnFinalizar;
    public static javax.swing.JButton btnSiguiente;
    public static javax.swing.JButton btnVerImagen;
    public static javax.swing.JButton btnVerTexto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JLabel labelImagen;
    public static javax.swing.JLabel labelNumero;
    public static javax.swing.JLabel labelSubtema;
    public static GUI.panelPregunta1 panelPregunta11;
    public static GUI.panelPregunta2 panelPregunta21;
    public static GUI.panelPregunta3 panelPregunta31;
    public static java.awt.TextArea txtExplicacion;
    // End of variables declaration//GEN-END:variables
}
