/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.controllerAgregarImagen;
import Controller.controllerAgregarPregunta;
import Controller.controllerEliminarPregunta;
import Controller.controllerModificarPregunta;
import static GUI.panelSubtemas.dlm;
import java.awt.Dimension;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author Mariano
 */
public class panelModificar extends javax.swing.JPanel {
     controllerModificarPregunta controller;
     controllerEliminarPregunta controller2;
     controllerAgregarImagen controller3;
     
    /**
     * Creates new form panelAgregar
     */
    public panelModificar() {

        initComponents();
        Dimension d3 = new Dimension(200,200);
        jScrollPane3.setSize(d3);
        jScrollPane3.setMaximumSize(d3);
        jScrollPane3.setMinimumSize(d3);
        jScrollPane3.setPreferredSize(d3);
        controller = new controllerModificarPregunta();
        controller2 = new controllerEliminarPregunta();
        controller3 = new controllerAgregarImagen();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnCrearPregunta = new javax.swing.JButton();
        btnCargarImagen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtExplicacion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelPregunta31 = new javax.swing.JTabbedPane();
        panelPregunta11 = new GUI.panelPregunta1();
        panelPregunta21 = new GUI.panelPregunta2();
        panelPregunta32 = new GUI.panelPregunta3();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSubTema = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        imagenLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idTxt = new java.awt.TextField();

        btnCrearPregunta.setText("Modificar");
        btnCrearPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPreguntaActionPerformed(evt);
            }
        });

        btnCargarImagen.setText("Cargar");
        btnCargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarImagenActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de Explicación:");

        txtExplicacion.setColumns(20);
        txtExplicacion.setRows(5);
        jScrollPane1.setViewportView(txtExplicacion);

        jLabel3.setText("Textual:");

        jLabel4.setText("Imagen:");

        jLabel5.setText("Escoja Subtema:");

        panelPregunta31.addTab("Patron 1", panelPregunta11);
        panelPregunta31.addTab("Patron 2", panelPregunta21);
        panelPregunta31.addTab("Patron 3", panelPregunta32);

        listSubTema.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listSubTema);

        jScrollPane3.setViewportView(imagenLabel);

        jLabel1.setText("ID:");

        idTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPregunta31, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCargarImagen)
                                    .addComponent(jLabel4))
                                .addGap(84, 84, 84)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearPregunta)
                .addGap(225, 225, 225))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPregunta31, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(btnCargarImagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearPregunta)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(150, 150, 150))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarImagenActionPerformed
    JFileChooser seleccionado = new JFileChooser();
    File archivo;
    byte[] bytesImg;
    if(seleccionado.showDialog(null, "ABRIR ARCHIVO") == JFileChooser.APPROVE_OPTION){
        archivo = seleccionado.getSelectedFile();
            if(archivo.canRead()){
                if(archivo.getName().endsWith("jpg")||archivo.getName().endsWith("png")||archivo.getName().endsWith("gif")){
                    bytesImg = controller3.aperturaImagen(archivo);
                    imagenLabel.setIcon(new ImageIcon(bytesImg));
                    txtExplicacion.setText(archivo.getAbsolutePath());
                    txtExplicacion.setEditable(false);
                }else{
                    JOptionPane.showMessageDialog(null, "Por favor seleccione un archivo de tipo imagen.");
                 }
                
            }
        }
    
     
        
        
    }//GEN-LAST:event_btnCargarImagenActionPerformed

    private void btnCrearPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPreguntaActionPerformed
        ArrayList<String> preguntaTipo = new ArrayList();
        preguntaTipo.add("");
        preguntaTipo.add("");
        preguntaTipo.add("");
        preguntaTipo.add("");
        preguntaTipo.add("");
        preguntaTipo.add("");
        preguntaTipo.add("");
        String TipoPregunta = "";
        boolean interruptor=true;
        
        
        
        if (!(idTxt.getText().isEmpty()))
        {
        preguntaTipo.add(0,idTxt.getText());
        try {
        TipoPregunta = controller.tipoPregunta(idTxt.getText());
          } catch (Exception ex) {
                Logger.getLogger(panelModificar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Panel 1
         
        if(TipoPregunta.equals("1"))
        {
        if (!((panelPregunta11.txtPregunta.getText()).isEmpty()))
        {preguntaTipo.add(1,panelPregunta11.txtPregunta.getText());}
        
        if (  (panelPregunta11.txtA.getText()).isEmpty() &&
              (panelPregunta11.txtB.getText()).isEmpty() &&
              (panelPregunta11.txtC.getText()).isEmpty() &&
              (panelPregunta11.txtD.getText()).isEmpty() )
        {}
        else if((panelPregunta11.txtB.getText()).isEmpty() &&
              (panelPregunta11.txtC.getText()).isEmpty() &&
              (panelPregunta11.txtD.getText()).isEmpty())
        {         preguntaTipo.add(2,
                     panelPregunta11.txtA.getText()
                    );
        
        }
        else if(
              (panelPregunta11.txtC.getText()).isEmpty() &&
              (panelPregunta11.txtD.getText()).isEmpty())
        {
                     preguntaTipo.add(2,
                     panelPregunta11.txtA.getText()+"☺"+
                     panelPregunta11.txtB.getText()

                    );
        
        }        
        else if(
              (panelPregunta11.txtD.getText()).isEmpty())
        {
                     preguntaTipo.add(2,
                     panelPregunta11.txtA.getText()+"☺"+
                     panelPregunta11.txtB.getText()+"☺"+
                     panelPregunta11.txtC.getText()

                    );
        
        }
        else 
        {            preguntaTipo.add(2,
                     panelPregunta11.txtA.getText()+"☺"+
                     panelPregunta11.txtB.getText()+"☺"+
                     panelPregunta11.txtC.getText()+"☺"+
                     panelPregunta11.txtD.getText()

                    );
        
        }        
        
        if (!(txtExplicacion.getText().isEmpty()))
            {
                preguntaTipo.add(4,txtExplicacion.getText());
            }
       
        if (panelPregunta11.radioA.isSelected())
        {preguntaTipo.add(3,panelPregunta11.txtA.getText());}
        else if (panelPregunta11.radioB.isSelected())
        {preguntaTipo.add(3,panelPregunta11.txtB.getText());}
        else if (panelPregunta11.radioC.isSelected())
        {preguntaTipo.add(3,panelPregunta11.txtC.getText());}        
        else if (panelPregunta11.radioD.isSelected())
        {preguntaTipo.add(3,panelPregunta11.txtD.getText());}
        
        if(!(listSubTema.isSelectionEmpty())){
        preguntaTipo.add(5,(String) listSubTema.getSelectedValue());
        }          
        
        }
        
        //Panel 2
        else if(TipoPregunta.equals("2"))
        {
         if (!((panelPregunta21.txtPregunta.getText()).isEmpty() &&(panelPregunta21.txtPregunta1.getText().isEmpty())))
        {preguntaTipo.add(1,panelPregunta21.txtPregunta.getText()+" "+panelPregunta21.txtPregunta1.getText());}
        
        if (  (panelPregunta21.txtA.getText()).isEmpty() &&
              (panelPregunta21.txtB.getText()).isEmpty() &&
              (panelPregunta21.txtC.getText()).isEmpty() &&
              (panelPregunta21.txtD.getText()).isEmpty() )
        {}
        else if((panelPregunta21.txtB.getText()).isEmpty() &&
              (panelPregunta21.txtC.getText()).isEmpty() &&
              (panelPregunta21.txtD.getText()).isEmpty())
        {         preguntaTipo.add(2,
                     panelPregunta21.txtA.getText()
                    );
        
        }
        else if(
              (panelPregunta21.txtC.getText()).isEmpty() &&
              (panelPregunta21.txtD.getText()).isEmpty())
        {
                     preguntaTipo.add(2,
                     panelPregunta21.txtA.getText()+"☺"+
                     panelPregunta21.txtB.getText()

                    ); 
        
        }        
        else if(
              (panelPregunta21.txtD.getText()).isEmpty())
        {
                     preguntaTipo.add(2,
                     panelPregunta21.txtA.getText()+"☺"+
                     panelPregunta21.txtB.getText()+"☺"+
                     panelPregunta21.txtC.getText()

                    );
        
        }
        else 
        {            preguntaTipo.add(2,
                     panelPregunta21.txtA.getText()+"☺"+
                     panelPregunta21.txtB.getText()+"☺"+
                     panelPregunta21.txtC.getText()+"☺"+
                     panelPregunta21.txtD.getText()

                    );
        
        }        
        
        if (!(txtExplicacion.getText().isEmpty()))
            {
                preguntaTipo.add(4,txtExplicacion.getText());
            }
       
        if (panelPregunta21.radioA.isSelected())
        {preguntaTipo.add(3,panelPregunta21.txtA.getText());}
        else if (panelPregunta21.radioB.isSelected())
        {preguntaTipo.add(3,panelPregunta21.txtB.getText());}
        else if (panelPregunta21.radioC.isSelected())
        {preguntaTipo.add(3,panelPregunta21.txtC.getText());}        
        else if (panelPregunta21.radioD.isSelected())
        {preguntaTipo.add(3,panelPregunta21.txtD.getText());}
        
        if(!(listSubTema.isSelectionEmpty())){
        preguntaTipo.add(5,(String) listSubTema.getSelectedValue());
        }
        }
        
        
        //Panel 3
        else if(TipoPregunta.equals("3"))
        {
        if (!((panelPregunta32.txtPregunta.getText()).isEmpty() && (panelPregunta32.txtArea31.getText().isEmpty()) &&(panelPregunta32.txtSegundo.getText().isEmpty())))
        {
        preguntaTipo.add(1,panelPregunta32.txtPregunta.getText()+" "+panelPregunta32.txtArea31.getText()+" "+panelPregunta32.txtSegundo.getText());
        }
        
        if (  (panelPregunta32.txtA.getText()).isEmpty() &&
              (panelPregunta32.txtB.getText()).isEmpty() &&
              (panelPregunta32.txtC.getText()).isEmpty() &&
              (panelPregunta32.txtD.getText()).isEmpty() )
        {}
        else if((panelPregunta32.txtB.getText()).isEmpty() &&
              (panelPregunta32.txtC.getText()).isEmpty() &&
              (panelPregunta32.txtD.getText()).isEmpty())
        {         preguntaTipo.add(2,
                     panelPregunta32.txtA.getText()
                    );
        
        }
        else if(
              (panelPregunta32.txtC.getText()).isEmpty() &&
              (panelPregunta32.txtD.getText()).isEmpty())
        {
                     preguntaTipo.add(2,
                     panelPregunta32.txtA.getText()+"☺"+
                     panelPregunta32.txtB.getText()

                    );
        
        }        
        else if(
              (panelPregunta32.txtD.getText()).isEmpty())
        {
                     preguntaTipo.add(2,
                     panelPregunta32.txtA.getText()+"☺"+
                     panelPregunta32.txtB.getText()+"☺"+
                     panelPregunta32.txtC.getText()

                    );
        
        }
        else 
        {            preguntaTipo.add(2,
                     panelPregunta32.txtA.getText()+"☺"+
                     panelPregunta32.txtB.getText()+"☺"+
                     panelPregunta32.txtC.getText()+"☺"+
                     panelPregunta32.txtD.getText()

                    );
        
        }        
        
        if (!(txtExplicacion.getText().isEmpty()))
            {
                preguntaTipo.add(4,txtExplicacion.getText());
            }
       
        if (panelPregunta32.radioA.isSelected())
        {preguntaTipo.add(3,panelPregunta32.txtA.getText());}
        else if (panelPregunta32.radioB.isSelected())
        {preguntaTipo.add(3,panelPregunta32.txtB.getText());}
        else if (panelPregunta32.radioC.isSelected())
        {preguntaTipo.add(3,panelPregunta32.txtC.getText());}        
        else if (panelPregunta32.radioD.isSelected())
        {preguntaTipo.add(3,panelPregunta32.txtD.getText());}
        
        if(!(listSubTema.isSelectionEmpty())){
            
        preguntaTipo.add(5,(String) listSubTema.getSelectedValue());
        }            
        
        }

        
        }
        
        else{
            interruptor=false;
        
        }
        
        
        
        
      

        boolean flag = false;
         try {

           
           flag = controller.ModificarPregunta(preguntaTipo);
           
           if (interruptor==false)
           {
           flag = false;
           }

         } catch (Exception ex) {
             Logger.getLogger(panelModificar.class.getName()).log(Level.SEVERE, null, ex);
         }
        if(flag)JOptionPane.showMessageDialog(null, "Pregunta modificada!");
        else JOptionPane.showMessageDialog(null, "Pregunta no modificada!");
        
        
        
        {
        }

        
    }//GEN-LAST:event_btnCrearPreguntaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarImagen;
    private javax.swing.JButton btnCrearPregunta;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.TextField idTxt;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JList listSubTema;
    private GUI.panelPregunta1 panelPregunta11;
    private GUI.panelPregunta2 panelPregunta21;
    private javax.swing.JTabbedPane panelPregunta31;
    private GUI.panelPregunta3 panelPregunta32;
    private javax.swing.JTextArea txtExplicacion;
    // End of variables declaration//GEN-END:variables
}
