/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.controllerEliminarPregunta;
import java.io.IOError;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Mariano
 */
public class panelEliminar extends javax.swing.JPanel {
    controllerEliminarPregunta controller;

    /**
     * Creates new form panelEliminar
     */
    public panelEliminar() {
        initComponents();
        txtPreguntas.setEditable(false);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        txtPreguntas = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        txtPreguntas.setColumns(20);
        txtPreguntas.setRows(5);
        txtPreguntas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtPreguntasPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(txtPreguntas);

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Digite el ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtID)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(411, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller = new controllerEliminarPregunta();
        
        boolean flag = false;
         try {
             
             flag = controller.EliminarPreguntas(txtID.getText());
             txtPreguntas.setText(controller.mostrarPreguntas());
             
         } catch (Exception ex) {
             Logger.getLogger(panelAgregar.class.getName()).log(Level.SEVERE, null, ex);
         }
         
         try {
             
             txtPreguntas.setText(controller.mostrarPreguntas());
             
         } catch (Exception ex) {
             Logger.getLogger(panelAgregar.class.getName()).log(Level.SEVERE, null, ex);
         } 
         
         catch (Throwable t){
                    if(t instanceof Exception){
                        if(t instanceof IOException){
                            
                        }  else {
                           
                        }
                    } else if (t instanceof Error){
                        if(t instanceof IOError){
                            // handle this Error
                        }  else {
                           
                        }
                    } else {

                        throw t;
                    }
                }
         
         
        if(flag)JOptionPane.showMessageDialog(null, "Eliminado !");
        else JOptionPane.showMessageDialog(null, "No Eliminado !");
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPreguntasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtPreguntasPropertyChange
      controller = new controllerEliminarPregunta();
        
        boolean flag = false;
         try {
             
             
             txtPreguntas.setText(controller.mostrarPreguntas());
              
             flag = true;
         } catch (Exception ex) {
         }
        if(flag);
        else;
    }//GEN-LAST:event_txtPreguntasPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtID;
    public javax.swing.JTextArea txtPreguntas;
    // End of variables declaration//GEN-END:variables
}
